apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-ecr-secrets-operator.name" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-ecr-secrets-operator.name" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kube-ecr-secrets-operator.name" . }}-controller-manager
  namespace: {{ .Release.Namespace }}