apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-ecr-secrets-operator.name" . }}-webhook-service
  labels:
{{- include "kube-ecr-secrets-operator.selectorLabels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    control-plane: controller-manager