apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mutate-awsecrcredential
  failurePolicy: Fail
  name: ecrcredential.zakariaamine.com
  rules:
  - apiGroups:
    - aws.zakariaamine.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsecrimagepullsecrets
    - clusterawsecrimagepullsecrets
  sideEffects: NoneOnDryRun