//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSECRImagePullSecret) DeepCopyInto(out *AWSECRImagePullSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSECRImagePullSecret.
func (in *AWSECRImagePullSecret) DeepCopy() *AWSECRImagePullSecret {
	if in == nil {
		return nil
	}
	out := new(AWSECRImagePullSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSECRImagePullSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSECRImagePullSecretList) DeepCopyInto(out *AWSECRImagePullSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSECRImagePullSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSECRImagePullSecretList.
func (in *AWSECRImagePullSecretList) DeepCopy() *AWSECRImagePullSecretList {
	if in == nil {
		return nil
	}
	out := new(AWSECRImagePullSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSECRImagePullSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSECRImagePullSecretSpec) DeepCopyInto(out *AWSECRImagePullSecretSpec) {
	*out = *in
	out.AWSAccess = in.AWSAccess
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSECRImagePullSecretSpec.
func (in *AWSECRImagePullSecretSpec) DeepCopy() *AWSECRImagePullSecretSpec {
	if in == nil {
		return nil
	}
	out := new(AWSECRImagePullSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSECRImagePullSecretStatus) DeepCopyInto(out *AWSECRImagePullSecretStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSECRImagePullSecretStatus.
func (in *AWSECRImagePullSecretStatus) DeepCopy() *AWSECRImagePullSecretStatus {
	if in == nil {
		return nil
	}
	out := new(AWSECRImagePullSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAWSECRImagePullSecret) DeepCopyInto(out *ClusterAWSECRImagePullSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAWSECRImagePullSecret.
func (in *ClusterAWSECRImagePullSecret) DeepCopy() *ClusterAWSECRImagePullSecret {
	if in == nil {
		return nil
	}
	out := new(ClusterAWSECRImagePullSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAWSECRImagePullSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAWSECRImagePullSecretList) DeepCopyInto(out *ClusterAWSECRImagePullSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterAWSECRImagePullSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAWSECRImagePullSecretList.
func (in *ClusterAWSECRImagePullSecretList) DeepCopy() *ClusterAWSECRImagePullSecretList {
	if in == nil {
		return nil
	}
	out := new(ClusterAWSECRImagePullSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAWSECRImagePullSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAWSECRImagePullSecretSpec) DeepCopyInto(out *ClusterAWSECRImagePullSecretSpec) {
	*out = *in
	out.AWSAccess = in.AWSAccess
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAWSECRImagePullSecretSpec.
func (in *ClusterAWSECRImagePullSecretSpec) DeepCopy() *ClusterAWSECRImagePullSecretSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAWSECRImagePullSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAWSECRImagePullSecretStatus) DeepCopyInto(out *ClusterAWSECRImagePullSecretStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAWSECRImagePullSecretStatus.
func (in *ClusterAWSECRImagePullSecretStatus) DeepCopy() *ClusterAWSECRImagePullSecretStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterAWSECRImagePullSecretStatus)
	in.DeepCopyInto(out)
	return out
}
