name: release

on:
  workflow_dispatch:
    inputs:
      release-version:
        type: string
        required: true

permissions: 
  packages: write
  contents: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: docker login
              run: echo "${{ github.token}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - name: build and push docker image
              run: docker build --push . -t ghcr.io/zak905/kube-ecr-secrets-operator/controller-manager:${{ inputs.release-version}}
            - uses: ncipollo/release-action@v1
              with:
                generateReleaseNotes: true
                makeLatest: true
                tag: ${{ inputs.release-version }}
            
            